name: CI Workflow

on:
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  terraform-job:
    runs-on: ubuntu-latest
    steps:

#checkout code
      - name: Checkout code
        uses: actions/checkout@v2


